### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by cyberchrime** [polyrainbow/steinmixer#1]
Hi @polyrainbow ,

thanks for your great work on a dspMixFx replacement. Would you mind adding a license to your project? In Germany, a project without a license is subject to copyright law, i.e. using your project in any manner is currently strictly prohibited.

UPDATE: just saw that there is a license mentioned in the package.json file. If you could add a separate LICENSE file, it would be really helpful finding this essential information.

**Comment by polyrainbow** [comment]
Sure, I've added the Apache License 2.0 as LICENSE file and in `package.json`. Thanks for your interest.
